version: "3.8"

services:
  lc-api:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lc-api
    ports:
      - "8082:8082"
    depends_on:
      - lc-postgres

  lc-postgres:
    restart: always
    image: postgres:14.13-alpine3.20
    container_name: lc-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - ./db/data:/docker-entrypoint-initdb.d

  lc-pgadmin:
    image: dpage/pgadmin4:latest
    container_name: lc-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - lc-postgres
