apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lc-postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lc-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lc-postgres
  template:
    metadata:
      labels:
        app: lc-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:14.13-alpine3.20
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "admin"
          volumeMounts:
            - mountPath: /docker-entrypoint-initdb.d
              name: db-init
      volumes:
        - name: db-init
          configMap:
            name: db-init-sql
---
apiVersion: v1
kind: Service
metadata:
  name: lc-postgres
spec:
  selector:
    app: lc-postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
